version: "3.8"
services:
    mongodb:
        image: mongo
        restart: always
        container_name: mongodb
        ports:
            - 27017:27017
        volumes:
            - data:/data
        environment:
            - MONGO_INITDB_ROOT_USERNAME=rootuser
            - MONGO_INITDB_ROOT_PASSWORD=rootpass
    mongo-express:
        image: mongo-express
        container_name: mongo-expressre
        restart: always
        ports:
            - 8081:8081
        environment:
            - ME_CONFIG_MONGODB_ADMINUSERNAME=rootuser
            - ME_CONFIG_MONGODB_ADMINPASSWORD=rootpass
            - ME_CONFIG_MONGODB_SERVER=mongodb
    web:
        build: .
        restart: always
        ports:
            - 3000:3000
        volumes:
            - .:/app
        command: air
        environment:
            - MONGO_URL=mongodb://rootuser:rootpass@mongodb:27017
        depends_on:
            - mongodb
volumes:
    data: {}

networks:
    default:
        name: mongodb_network